//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvaloniaSample.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AvaloniaSample.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Start  的本地化字符串。
        /// </summary>
        internal static string AutoStartEnabled {
            get {
                return ResourceManager.GetString("AutoStartEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display Prompt When Closing 的本地化字符串。
        /// </summary>
        internal static string DisplayPromptWhenClosing {
            get {
                return ResourceManager.GetString("DisplayPromptWhenClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Find In TrayIcon 的本地化字符串。
        /// </summary>
        internal static string FindInTrayIcon {
            get {
                return ResourceManager.GetString("FindInTrayIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Font 的本地化字符串。
        /// </summary>
        internal static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FontSize 的本地化字符串。
        /// </summary>
        internal static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide Tray Icon On Close 的本地化字符串。
        /// </summary>
        internal static string HideTrayIconOnClose {
            get {
                return ResourceManager.GetString("HideTrayIconOnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No More Prompts 的本地化字符串。
        /// </summary>
        internal static string NoMorePrompts {
            get {
                return ResourceManager.GetString("NoMorePrompts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Main Window 的本地化字符串。
        /// </summary>
        internal static string ShowMainWindow {
            get {
                return ResourceManager.GetString("ShowMainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to exit? 的本地化字符串。
        /// </summary>
        internal static string SureExit {
            get {
                return ResourceManager.GetString("SureExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        internal static string Tab_About_Language {
            get {
                return ResourceManager.GetString("Tab_About_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Theme 的本地化字符串。
        /// </summary>
        internal static string Tab_About_Theme {
            get {
                return ResourceManager.GetString("Tab_About_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        internal static string Tab_About_Title {
            get {
                return ResourceManager.GetString("Tab_About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Setting 的本地化字符串。
        /// </summary>
        internal static string Tab_Setting_Title {
            get {
                return ResourceManager.GetString("Tab_Setting_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User 的本地化字符串。
        /// </summary>
        internal static string Tab_User_Title {
            get {
                return ResourceManager.GetString("Tab_User_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Avalonia Test 的本地化字符串。
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Topmost 的本地化字符串。
        /// </summary>
        internal static string Topmost {
            get {
                return ResourceManager.GetString("Topmost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        internal static string TurnOff {
            get {
                return ResourceManager.GetString("TurnOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On 的本地化字符串。
        /// </summary>
        internal static string TurnOn {
            get {
                return ResourceManager.GetString("TurnOn", resourceCulture);
            }
        }
    }
}
